### ISSUE TITLE
Strange progress bar behavior when hover occurs

### ISSUE THREAD

**Issue by rn4n** [JPeer264/toastr2#1]
First of all, thank you for the awesome job removing the jQuery dependency from this lib.

I've got a problem when hover occurs on a toast with progress bar enabled.
I have a file to setup toast options:
```js
import Toastr from 'toastr2'
import '../../../node_modules/toastr2/dist/toastr.min.css'

export const toast = new Toastr({
    progressBar: true,
    closeButton: true
})
```
And then, I use it:
```js
import { toast } from "./toast";

toast.success(
    `Em 20/12/2019 00:00:00`,
    'Evento Registrado'
)
```
The behavior is: if a put the cursor on the toast, the progress bar goes crazy, as you can see on the image below:
<kbd>[![toast problem][1]][1]</kbd>

[1]:https://i.imgur.com/Vx9Rnd6.gif

**Comment by JPeer264** [comment]
Thanks for your issue. I still did not implemented all unit tests, so I have to check if those tests are failing on my implementation. I will look at that as soon as I have time (unfortunately next week, or you gonna check it and tell me or make a PR). 

Furthermore, do you know if this bug exists in the original toastr?

**Comment by rn4n** [comment]
Thank you. 

No, it does not exist.
I created a snippet using the original toastr here: https://jsfiddle.net/reebrone/f5ceuzLh/

When the cursor is on toast, the progress bar goes hidden and the progress value returns to 100%.

**Comment by JPeer264** [comment]
@reebr should work in `v3.0.0-alpha.8`. If you find any other issues, just open a new issue ;)
