### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by omerman** [JPeer264/toastr2#5]
When adding this lib to my project, I see no declaration file, therefor Im getting 

![image](https://user-images.githubusercontent.com/6780529/100745584-2b7d6700-33e8-11eb-9f6f-264f243cc305.png)

These are the installed files (node_modules)
![image](https://user-images.githubusercontent.com/6780529/100745848-8b740d80-33e8-11eb-8b88-c50d315c83a2.png)

Help?

**Comment by JPeer264** [comment]
Alright, seems like the typings are not generated. I will investigate

**Comment by JPeer264** [comment]
v`3.0.0-alpha.17` should fix this. Thanks for filling this issue

**Comment by omerman** [comment]
@JPeer264 Thanks for the quick response! 
Looks good, works great :)

**Comment by JPeer264** [comment]
Glad to hear that 💯
